# Generated by Django 5.0.4 on 2024-04-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='lastname',
        ),
        migrations.AlterModelTable(
            name='bubbletea',
            table='app_bubbletea',
        ),
        migrations.AlterModelTable(
            name='bubbletea_topping',
            table='app_bubbletea_topping',
        ),
        migrations.AlterModelTable(
            name='drink',
            table='app_drink',
        ),
        migrations.AlterModelTable(
            name='order',
            table='app_order',
        ),
        migrations.AlterModelTable(
            name='order_drink',
            table='app_order_drink',
        ),
        migrations.AlterModelTable(
            name='topping',
            table='app_topping',
        ),
        migrations.AlterModelTable(
            name='user',
            table='app_user',
        ),
    ]
