# Generated by Django 5.0.4 on 2024-04-18 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_surname_user_lastname_alter_bubbletea_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BubbleTea_Topping',
            new_name='Drink_Topping',
        ),
        migrations.RemoveField(
            model_name='drink_topping',
            name='bubbletea',
        ),
        migrations.AddField(
            model_name='drink',
            name='price',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='drink',
            name='sugar_quantity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drink_topping',
            name='drink',
            field=models.ForeignKey(default=6.0, on_delete=django.db.models.deletion.CASCADE, to='app.drink'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='drink_topping',
            table='app_drink_topping',
        ),
        migrations.DeleteModel(
            name='BubbleTea',
        ),
    ]
