# Generated by Django 5.0.4 on 2024-04-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_bubbletea_topping_drink_topping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='sugar_quantity',
        ),
        migrations.AddField(
            model_name='order_drink',
            name='sugar_quantity',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0),
            preserve_default=False,
        ),
    ]
