# Generated by Django 5.0.4 on 2024-04-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_bubbletea_topping_drink_topping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num_order',
            field=models.CharField(default='ID-YYYYMMDD', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
