# Generated by Django 5.0.4 on 2024-04-20 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_num_order_alter_drink_description'),
        ('app', '0004_remove_drink_sugar_quantity_and_more'),
    ]

    operations = [
    ]
