# Generated by Django 5.0.4 on 2024-04-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20240420_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_order',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
